/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'HT075' at '18-3-1 下午2:42' with Gradle 2.14.1
 *
 * @author HT075, @date 18-3-1 下午2:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
